// Real Twitch integration test. No API interception or embedded credentials.
const assert=require('assert/strict'),{promisify}=require('util'),run=promisify(require('child_process').execFile);
const {chromium,webkit}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');const base=process.env.LIVE_URL||'http://localhost:8765/twitchunblock/';
(async()=>{for(const [name,engine] of Object.entries({chromium,webkit})){
 const browser=await engine.launch();try{const page=await browser.newPage();await page.goto(base);await page.locator('#sign-in').click();await page.waitForFunction(()=>TwitchAuth.challenge);
 const activationURL=await page.evaluate(()=>TwitchAuth.challenge.url);if(process.env.TWITCH_APPROVAL_HELPER)await run(process.env.TWITCH_APPROVAL_HELPER,[activationURL]);else console.log('Approve this login in Twitch:',activationURL);await page.waitForFunction(()=>TwitchAuth.session?.userId,null,{timeout:90000});assert(await page.evaluate(async()=>Boolean(await TwitchAuth.validate())));
 const rows=await page.evaluate(()=>TwitchAPI.home());assert(rows.length);const live=rows[0];
 const offline=await page.evaluate(async()=>{for(const login of ['ninja','shroud','twitch','pokimane','lirik']){const c=await TwitchAPI.channel(login);if(!c.stream)return c;}return null});assert(offline);
 const exact=await page.evaluate(login=>TwitchAPI.search(login,false),offline.login);assert(exact.some(r=>r.login===offline.login));
 const videos=await page.evaluate(id=>TwitchAPI.videos(id),live.id);const clips=await page.evaluate(id=>TwitchAPI.clips(id),live.id);assert(clips.length);assert(clips.every(c=>c.url.startsWith('https://clips.twitch.tv/')));
 let vods=videos;if(!vods.length)vods=await page.evaluate(id=>TwitchAPI.videos(id),offline.id);assert(vods.length);assert(vods.every(v=>v.url.startsWith('https://www.twitch.tv/videos/')));
 for(const language of ['en','ar'])for(const width of [320,375,390,430,1440]){await page.setViewportSize({width,height:900});await page.evaluate(lang=>TwitchI18n.setLanguage(lang),language);for(const hash of ['home','search','channel/'+live.login,'channel/'+offline.login,'history','settings']){await page.goto(base+'#'+hash);if(hash.startsWith('channel/'))await page.waitForFunction(()=>document.querySelector('#channel-profile').getAttribute('aria-busy')==='false'&&document.querySelector('#channel-profile').children.length>0);if(hash==='home')await page.waitForFunction(()=>document.querySelector('#home-results').children.length>0);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(await page.locator('html').getAttribute('dir'),language==='ar'?'rtl':'ltr');}}
 await page.goto(base+'#search');await page.locator('#channel').fill(live.login);await page.locator('#search-form').evaluate(e=>e.requestSubmit());await page.waitForFunction(()=>document.querySelector('#search-results').children.length>0);await page.reload();assert(await page.evaluate(()=>TwitchAuth.session!==null));
 await page.evaluate(()=>{window.previousSession={...TwitchAuth.session};TwitchAuth.session.expiresAt=Date.now()-1;});await page.evaluate(()=>TwitchAuth.token().catch(()=>{}));assert.equal(await page.evaluate(()=>TwitchAuth.session),null);
 await page.evaluate(()=>sessionStorage.setItem('twitchunblock.session',JSON.stringify(window.previousSession)));await page.reload();await page.waitForFunction(()=>TwitchAuth.session?.userId);const revoked=await page.evaluate(async()=>{const token=TwitchAuth.session.token;TwitchAuth.logout();for(let i=0;i<10;i++){await new Promise(r=>setTimeout(r,500));const r=await fetch('https://id.twitch.tv/oauth2/validate',{headers:{Authorization:'OAuth '+token}});if(r.status===401)return true;}return false;});assert(revoked);assert.equal(await page.evaluate(()=>TwitchAuth.session),null);
 console.log('PASS REAL',name,JSON.stringify({login:true,validation:true,home:rows.length,exactSearch:true,live:true,offline:true,vods:vods.length,clips:clips.length,widths:5,languages:2,expired:true,logout:true,revoked401:true}));

 }finally{await browser.close();}}
})().catch(e=>{console.error('REAL test failed:',e.message);process.exit(1)});
