/* Deterministic mocked UX regressions, separate from tests/live.cjs. */
'use strict';
const assert=require('node:assert/strict');const {chromium,webkit}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const {setup,search,stream}=require('./phase2.cjs');
(async()=>{for(const [name,engine]of Object.entries({chromium,webkit})){const browser=await engine.launch();try{
 const {page,context,calls,errors}=await setup(browser,{width:390});await page.locator('#home-results .channel-card').waitFor();
 await page.locator('#home-results .channel-link').focus();await page.evaluate(()=>TwitchHome.refresh());assert(await page.locator('#home-results .channel-link').evaluate(el=>el===document.activeElement));
 await page.emulateMedia({reducedMotion:'no-preference'});await page.locator('#home-results').evaluate(el=>el.style.minHeight='2600px');await page.evaluate(()=>scrollTo({top:550,behavior:'instant'}));await page.waitForTimeout(100);await page.locator('#home-results .channel-link').first().evaluate(a=>a.click());await page.waitForFunction(()=>document.querySelector('#channel-profile').getAttribute('aria-busy')==='false'&&document.querySelector('#channel-profile .project-heading'));await page.goBack();await page.waitForFunction(()=>Math.abs(scrollY-550)<4);await page.locator('#home-results').evaluate(el=>el.style.minHeight='');await page.emulateMedia({reducedMotion:'reduce'});
 const first=calls.filter(c=>c.path==='/helix/streams').length;await page.locator('[data-section="settings"]').click();await page.locator('[data-section="home"]').click();await page.waitForFunction(()=>document.querySelector('#home-results').getAttribute('aria-busy')==='false');assert.equal(calls.filter(c=>c.path==='/helix/streams').length,first,'Home returns from cache');
 await page.route('https://api.twitch.tv/helix/streams**',async r=>{await new Promise(resolve=>setTimeout(resolve,150));await r.fulfill({contentType:'application/json',body:JSON.stringify({data:[stream]})});});
 await page.locator('#refresh-home').click();assert.equal(await page.locator('#home-results .channel-card').count(),1,'Refresh retains cards');await page.waitForFunction(()=>document.querySelector('#home-results').getAttribute('aria-busy')==='false');
 await search(page,'both');assert(page.url().includes('q=both'));await page.reload();await page.waitForFunction(()=>document.querySelector('#search-results').getAttribute('aria-busy')==='false'&&document.querySelector('#search-results .channel-card'));assert.equal(await page.locator('#channel').inputValue(),'both');assert.equal(await page.locator('#search-results .channel-card').count(),2);
 await page.unroute('https://api.twitch.tv/helix/streams**');
 const startCalls=calls.filter(c=>c.path==='/helix/clips').length;await page.goto((process.env.SITE_URL||'http://127.0.0.1:8765')+'/twitchunblock/#channel/livechannel');await page.locator('#channel-videos .media-link').waitFor();assert.equal(calls.filter(c=>c.path==='/helix/clips').length,startCalls,'Inactive tab is lazy');
 await page.locator('#save-channel').click();assert(await page.locator('#save-channel').evaluate(el=>el===document.activeElement),'Save preserves keyboard focus');
 let videoRequests=0;await page.route('https://api.twitch.tv/helix/videos**',r=>{const params=new URL(r.request().url()).searchParams;videoRequests++;return r.fulfill({contentType:'application/json',body:JSON.stringify({data:[{id:params.has('after')?'102':'101',title:params.has('after')?'Second archive':'First archive',created_at:'2026-10-01T12:00:00Z',duration:'1h',view_count:50,thumbnail_url:''}],pagination:params.has('after')?{}:{cursor:'nextpage'}})});});
 await page.locator('#retry-channel').click();await page.locator('#media-more').waitFor();await page.locator('#media-more').click();await page.waitForFunction(()=>document.querySelectorAll('#channel-videos .media-card').length===2);assert.equal(videoRequests,2);assert(await page.locator('#media-more').isHidden());
 await page.locator('#media-filter').fill('Second');assert.equal(await page.locator('#channel-videos .media-card').count(),1);await page.locator('#tab-clips').click();await page.locator('#clip-period').selectOption('7');await page.waitForFunction(()=>document.querySelector('#channel-clips').getAttribute('aria-busy')==='false');assert(calls.some(c=>c.path==='/helix/clips'&&new URLSearchParams(c.params).has('started_at')));
 await page.goBack();await page.waitForFunction(()=>document.querySelector('#clip-period').value==='all');await page.goBack();await page.waitForFunction(()=>document.querySelector('#tab-videos').getAttribute('aria-selected')==='true');assert.equal(await page.locator('#media-filter').inputValue(),'Second');assert.equal(await page.locator('#channel-videos .media-card').count(),1);
 await page.locator('[data-section="search"]').click();await page.locator('#channel').fill('live');await page.waitForFunction(()=>document.querySelector('#channel').getAttribute('aria-expanded')==='true');await page.locator('#channel').press('ArrowDown');await page.locator('#channel').press('Enter');await page.waitForFunction(()=>location.hash.startsWith('#channel/'));assert(await page.locator('#search-suggestions').isHidden());
 await page.locator('[data-section="home"]').click();await page.locator('[data-home-view="saved"]').click();await page.waitForFunction(()=>document.querySelector('[data-home-view="saved"]').hasAttribute('aria-current'));await page.locator('#home-results .channel-card').waitFor();await page.locator('[data-section="settings"]').click();await page.locator('#clear-saved').click();assert.equal(await page.evaluate(()=>TwitchDiscovery.list().length),0);assert((await page.evaluate(()=>TwitchHistory.list())).length>0);
 await page.setViewportSize({width:844,height:390});await page.evaluate(()=>TwitchI18n.setLanguage('ar'));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 assert.equal(await page.evaluate(()=>Object.values(localStorage).some(v=>v.includes('testtokenonly'))),false);assert.deepEqual(errors,[]);await context.close();
 console.log('PASS',name,'MOCKED P0 cache/refresh, routed search reload, lazy media, pagination, filters, clip dates, Back/Forward, combobox, save focus/privacy');
}finally{await browser.close();}}})().catch(error=>{console.error(error);process.exit(1)});
